### ISSUE TITLE
Put a link to the site in the description field of this site.

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/juliagraphs.github.io#2]
It appears to be customary for the Description field of this repo to point to the site that it generates.

**Comment by sbromberger** [comment]
just a comment: until this site is "production-ready", feel free to review and merge your own commits :) I don't know whether that needed to be said.

**Comment by jpfairbanks** [comment]
I don't have commit priv. I think you should make me a co-worker on the juliagraphs org. 

James Fairbanks, PhD

**Comment by sbromberger** [comment]
Gah. Let me see what went wrong w your access. Sorry. You should have had commit privs for a while now!
